subprojects {
	apply plugin: 'java-library'
	apply plugin: 'maven-publish'

	version = rootProject.mod_version
	group = rootProject.maven_group

	base {
		archivesName = "${rootProject.archives_base_name}-${project.name}"
	}

	repositories {
		mavenCentral()
		maven { url = 'https://maven.blamejared.com' }
		exclusiveContent {
			forRepository {
				maven { url = 'https://api.modrinth.com/maven' }
			}
			filter { includeGroup('maven.modrinth') }
		}
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
		withSourcesJar()
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
		options.release = 25
	}

	tasks.withType(GenerateModuleMetadata).configureEach {
		enabled = false
	}
}
