# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=1.21
java_version=21

# Mappings
parchment_minecraft_version=1.21
parchment_version=2024.07.28

# Fabric
loader_version=0.16.10
fabric_version=0.102.0+1.21

# NeoForge
neoforge_version=21.0.167

# Mod Properties
mod_version=1.1.0
maven_group=com.jomlom.recipebookaccess
archives_base_name=recipebookaccess
mod_id=recipebookaccess
mod_name=Recipe Book Access
