# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=1.20.1
java_version=17

# Mappings
parchment_minecraft_version=1.20.1
parchment_version=2023.09.03

# Fabric
loader_version=0.16.10
fabric_version=0.92.5+1.20.1

# NeoForge
neoforge_version=47.4.5

# Mod Properties
mod_version=1.2.0
maven_group=com.jomlom.recipebookaccess
archives_base_name=recipebookaccess
mod_id=recipebookaccess
mod_name=Recipe Book Access
