plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.20'
}

loom {
	splitEnvironmentSourceSets()
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"

	compileOnly("mezz.jei:jei-26.2-fabric:30.29.0.201") {
		transitive = false
	}
}

tasks.jar { enabled = false }
tasks.named('sourcesJar') { enabled = false }
