plugins {
	id 'fabric-loom' version '1.14.10'
}

loom {
	splitEnvironmentSourceSets()
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_version}@zip")
	}

	modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"

	modCompileOnly("mezz.jei:jei-1.21-fabric:19.8.2.99") {
		transitive = false
	}
}

tasks.jar { enabled = false }
tasks.named('sourcesJar') { enabled = false }
