plugins {
	id 'net.neoforged.moddev' version '2.0.144'
}

sourceSets {
	main {
		java.srcDir project(':common').file('src/main/java')
		resources.srcDir project(':common').file('src/main/resources')
		java.srcDir project(':common').file('src/client/java')
		resources.srcDir project(':common').file('src/client/resources')
	}
}

dependencies {
	implementation("mezz.jei:jei-1.21.11-neoforge:27.30.0.79") {
		transitive = false
	}
}

neoForge {
	version = rootProject.neoforge_version

	parchment {
		minecraftVersion = rootProject.parchment_minecraft_version
		mappingsVersion = rootProject.parchment_version
	}

	mods {
		"recipebookaccess" {
			sourceSet sourceSets.main
		}
	}

	runs {
		client {
			client()
		}
		server {
			server()
		}
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": inputs.properties.version, "mod_name": rootProject.mod_name, "mod_id": rootProject.mod_id
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from(rootProject.file("LICENSE")) {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = "${rootProject.archives_base_name}-neoforge"
			from components.java
		}
	}
}
